// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/spotahome/redis-operator/client/k8s/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// RedisFailovers returns a RedisFailoverInformer.
	RedisFailovers() RedisFailoverInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// RedisFailovers returns a RedisFailoverInformer.
func (v *version) RedisFailovers() RedisFailoverInformer {
	return &redisFailoverInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
