// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	context "context"
	time "time"

	apiredisfailoverv1 "github.com/spotahome/redis-operator/api/redisfailover/v1"
	versioned "github.com/spotahome/redis-operator/client/k8s/clientset/versioned"
	internalinterfaces "github.com/spotahome/redis-operator/client/k8s/informers/externalversions/internalinterfaces"
	redisfailoverv1 "github.com/spotahome/redis-operator/client/k8s/listers/redisfailover/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RedisFailoverInformer provides access to a shared informer and lister for
// RedisFailovers.
type RedisFailoverInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() redisfailoverv1.RedisFailoverLister
}

type redisFailoverInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRedisFailoverInformer constructs a new informer for RedisFailover type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRedisFailoverInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRedisFailoverInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRedisFailoverInformer constructs a new informer for RedisFailover type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRedisFailoverInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatabasesV1().RedisFailovers(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DatabasesV1().RedisFailovers(namespace).Watch(context.TODO(), options)
			},
		},
		&apiredisfailoverv1.RedisFailover{},
		resyncPeriod,
		indexers,
	)
}

func (f *redisFailoverInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRedisFailoverInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *redisFailoverInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apiredisfailoverv1.RedisFailover{}, f.defaultInformer)
}

func (f *redisFailoverInformer) Lister() redisfailoverv1.RedisFailoverLister {
	return redisfailoverv1.NewRedisFailoverLister(f.Informer().GetIndexer())
}
