apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
  haproxy:
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
        ephemeral-storage: 100Mi
      limits:
        memory: 500Mi
        ephemeral-storage: 100Mi
