// Code generated by lister-gen. DO NOT EDIT.

package v1

// RedisFailoverListerExpansion allows custom methods to be added to
// RedisFailoverLister.
type RedisFailoverListerExpansion interface{}

// RedisFailoverNamespaceListerExpansion allows custom methods to be added to
// RedisFailoverNamespaceLister.
type RedisFailoverNamespaceListerExpansion interface{}
