// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	redisfailoverv1 "github.com/spotahome/redis-operator/api/redisfailover/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RedisFailoverLister helps list RedisFailovers.
// All objects returned here must be treated as read-only.
type RedisFailoverLister interface {
	// List lists all RedisFailovers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*redisfailoverv1.RedisFailover, err error)
	// RedisFailovers returns an object that can list and get RedisFailovers.
	RedisFailovers(namespace string) RedisFailoverNamespaceLister
	RedisFailoverListerExpansion
}

// redisFailoverLister implements the RedisFailoverLister interface.
type redisFailoverLister struct {
	listers.ResourceIndexer[*redisfailoverv1.RedisFailover]
}

// NewRedisFailoverLister returns a new RedisFailoverLister.
func NewRedisFailoverLister(indexer cache.Indexer) RedisFailoverLister {
	return &redisFailoverLister{listers.New[*redisfailoverv1.RedisFailover](indexer, redisfailoverv1.Resource("redisfailover"))}
}

// RedisFailovers returns an object that can list and get RedisFailovers.
func (s *redisFailoverLister) RedisFailovers(namespace string) RedisFailoverNamespaceLister {
	return redisFailoverNamespaceLister{listers.NewNamespaced[*redisfailoverv1.RedisFailover](s.ResourceIndexer, namespace)}
}

// RedisFailoverNamespaceLister helps list and get RedisFailovers.
// All objects returned here must be treated as read-only.
type RedisFailoverNamespaceLister interface {
	// List lists all RedisFailovers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*redisfailoverv1.RedisFailover, err error)
	// Get retrieves the RedisFailover from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*redisfailoverv1.RedisFailover, error)
	RedisFailoverNamespaceListerExpansion
}

// redisFailoverNamespaceLister implements the RedisFailoverNamespaceLister
// interface.
type redisFailoverNamespaceLister struct {
	listers.ResourceIndexer[*redisfailoverv1.RedisFailover]
}
