// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/spotahome/redis-operator/api/redisfailover/v1"
	redisfailoverv1 "github.com/spotahome/redis-operator/client/k8s/clientset/versioned/typed/redisfailover/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRedisFailovers implements RedisFailoverInterface
type fakeRedisFailovers struct {
	*gentype.FakeClientWithList[*v1.RedisFailover, *v1.RedisFailoverList]
	Fake *FakeDatabasesV1
}

func newFakeRedisFailovers(fake *FakeDatabasesV1, namespace string) redisfailoverv1.RedisFailoverInterface {
	return &fakeRedisFailovers{
		gentype.NewFakeClientWithList[*v1.RedisFailover, *v1.RedisFailoverList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("redisfailovers"),
			v1.SchemeGroupVersion.WithKind("RedisFailover"),
			func() *v1.RedisFailover { return &v1.RedisFailover{} },
			func() *v1.RedisFailoverList { return &v1.RedisFailoverList{} },
			func(dst, src *v1.RedisFailoverList) { dst.ListMeta = src.ListMeta },
			func(list *v1.RedisFailoverList) []*v1.RedisFailover { return gentype.ToPointerSlice(list.Items) },
			func(list *v1.RedisFailoverList, items []*v1.RedisFailover) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
