name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    name: Golang Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=15m

  codegen-up-to-date:
    name: Code generation up-to-date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kubebuilder client and CRD up-to-date
        run: |
          make update-codegen generate-crd
      - name: Check for changes in generated files
        run: |
          git diff --exit-code
      - name: Fail if changes detected
        if: steps.codegen-up-to-date.outputs.exit_code != 0
        run: |
          exit 1

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make ci-unit-test

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [check, codegen-up-to-date, unit-test]
    strategy:
      matrix:
        kubernetes:
          - 1.21.14
          - 1.24.16
          - 1.25.12
          - 1.26.7
          - 1.27.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install conntrack
        run: sudo apt-get install -y conntrack
      - uses: medyagh/setup-minikube@v0.0.14
        with:
          kubernetes-version: ${{ matrix.kubernetes }}
          minikube-version: 1.31.1
          driver: none
      - name: Add redisfailover CRD
        run: kubectl create -f manifests/databases.spotahome.com_redisfailovers.yaml
      - run: make ci-integration-test

  chart-test:
    name: Chart testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.2

      - name: Helm test
        run: make helm-test
