name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  DOCKER_METADATA_PR_HEAD_SHA: true

jobs:
  check:
    name: Golang Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --timeout=15m

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - run: make test-unit-ci

  integration-test:
    name: Integration test
    runs-on: ubuntu-22.04
    needs:
      - check
      - unit-test
    strategy:
      matrix:
        kubernetes:
          - 1.21.14
          - 1.22.17
          - 1.23.17
          - 1.24.16
          - 1.25.12
          - 1.26.7
          - 1.27.3
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Install conntrack
        run: sudo apt-get install -y conntrack
      - uses: medyagh/setup-minikube@v0.0.14
        with:
          kubernetes-version: ${{ matrix.kubernetes }}
          minikube-version: 1.31.1
          driver: none
      - name: Add redisfailover CRD
        run: kubectl create -f manifests/databases.spotahome.com_redisfailovers.yaml
      - run: make test-integration-ci

  chart-test:
    name: Chart testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.2

      - name: Helm test
        run: make test-helm-ci

  dockerhub-image:
    needs:
      - check
      - unit-test
      - integration-test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: powerhome/redis-operator
          tags: |
            type=semver,pattern={{raw}}
            type=sha,prefix=,suffix=,format=long
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/bake-action@v5
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: build
          push: true
